spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2467
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 438059515778-cpsvm35adfscaru0g90gvp55fst7rbm4.apps.googleusercontent.com
            client-secret: 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

