spring:
  application:
    name: demo
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 438059515778-cpsvm35adfscaru0g90gvp55fst7rbm4.apps.googleusercontent.com
            client-secret: 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

